### PR TITLE
allow y-stride in makeBasicImageView()

### PR DESCRIPTION
**Pull request by hmeine**
I would like this to be reviewed, although I am quite confident myself that this is a good change.

### CODE REVIEW

**Comment by ukoethe** [comment]
> I would like this to be reviewed

In the future, **all** changes should go through pull requests to avoid breaking the tests on master. (This happend yesterday due to a timeout on Travis that's hopefully fixed now). Announcing "build failing" on the front page is just too ugly.

Regarding the present change: please add a test to convince yourself and me that it works.

**Comment by hmeine** [comment]
Actually, there already is a (succeeding) test, and IIRC we could both not see the problem with that.  Now I found that it actually extracts the ROI as MA, not as view.  Therefore, the roi is not actually strided.

**Comment by hmeine** [comment]
OK, does the following sound like a plan?
1. I rebase this branch on current master (which changed due to my recent push) and force-push again.
2. After you merged the pull request (maybe you are waiting for the Travis CI?) into master, one of us merges master into the 1.11 branch.
Afterwards, I would only create PRs against the branch (even though I do not really see why master is not sufficient).

**Comment by ukoethe** [comment]
Don't worry, I'll merge this manually on my local machine. Just have to wait for the test of my latest changes to complete.

**Comment by ukoethe** [comment]
BTW, I noticed some TIFF-related branches in your fork. Is there anything we should merge into upstream?

**Comment by hmeine** [comment]
Just to summarize the state again: This PR makes the existing unit test for strided makeBasicImageView()s working, i.e. non-tautologic.  Consequently, the test fails without the change to makeBasicImageView().

**Comment by ukoethe** [comment]
I merged the PR into `version-1-11-rc`and about half of the tests already got through, so it's looking good.

**Pull request closed without merging**
