### PR TITLE
remove more Nose usage

### PR DESCRIPTION
**Pull request by a-detiste**
This is a follow-up to https://github.com/ukoethe/vigra/pull/545 

@hmaarrfk  @eli-schwartz

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Could you also try to address the low hanging fruit of bool8 in bumpy

I think this should help

https://github.com/numpy/numpy/issues/23755

**Comment by a-detiste** [comment]
I don't really see how it's related

**Comment by a-detiste** [comment]
Ok now I see...

**Comment by hmaarrfk** [comment]
Remind me why this isn’t a problem on master? The nose modifications that is

**Comment by hmaarrfk** [comment]
(You can set a similar upper bound to windows for numpy or if you are capable you may choose to fix the underlying issues)

**Comment by a-detiste** [comment]
I don't use windows or conda or even virtualenv, I stay on the Debian testing rolling release; which is today still at Numpy 1.x. This PR looks good so far.

**Comment by hmaarrfk** [comment]
I guess remains: `assert_raises`.

The remaining failures in OSX are likely due to compiler strictness I've encountered in https://github.com/conda-forge/vigra-feedstock/issues/134

**Comment by a-detiste** [comment]
this needs more research ...

Is it ok to try this as you suggested here https://github.com/ukoethe/vigra/pull/545 ? (this can be an other PR)

-from nose.tools import assert_raises
+from unittest import assertRaises as assert_raises

**Comment by hmaarrfk** [comment]
See #565

**Pull request merged**
