### PR TITLE
Multideftests

### PR DESCRIPTION
**Pull request by dagophil**
Added vigranumpy tests for functions that were exported via multidef.

### CODE REVIEW

**Comment by ukoethe** [comment]
What happened to the distance transform problem we talked about?

**Comment by dagophil** [comment]
I planned to add the commits for the distance transform fix in a separate pull request. Should I instead put them here?

**Comment by ukoethe** [comment]
Yes, just add them here, the PR will be updated automatically.

**Comment by dagophil** [comment]
About c060eef: The function `vigra.filters.distanceTransform` was defined multiple times. The new definition in `morphology.cxx` was ignored because of the old definition in `__init__.py`. I just threw out the old definition, since it is not needed anymore.

**Comment by ukoethe** [comment]
Now the test doesn't work anymore...

**Comment by ukoethe** [comment]
Merged into version-1-11-rc branch.

**Pull request closed without merging**
