### PR TITLE
Enhancements to unique() and relabelConsecutive()

### PR DESCRIPTION
**Pull request by stuarteberg**
Here are two tiny changes to make it easier for users to replace the horribly slow `numpy.unique()` with `vigra.analysis.unique()`:
- Support `int64`. (This is more commonly needed than I originally thought.)
- Sort the output by default, like `numpy.unique()` does.

### CODE REVIEW

**Comment by stuarteberg** [comment]
The CI failures above seem to be unrelated to this PR.  It's puzzling that they fail here, yet apparently passed on the master branch.  (This PR was based on the latest master.)

Failure details:

- Xcode 7.3, Python 3:

    ```
-- Could NOT find VIGRANUMPY_DEPENDENCIES (missing:  Boost_PYTHON_LIBRARY) 
CMake Error at config/FindVIGRANUMPY_DEPENDENCIES.cmake:240 (MESSAGE):
    vigranumpy dependencies NOT found while TEST_VIGRANUMPY=1
Call Stack (most recent call first):
  CMakeLists.txt:174 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/Users/travis/build/ukoethe/vigra/build/CMakeFiles/CMakeOutput.log".
    ```

(all other Travis configurations passed)

- AppVeyor:

    ```
Activating environment "C:\Miniconda-x64\envs\python"...
The input line is too long.
 "PATH_NO_SCRIPTS=C:\Miniconda-x64\envs\python;C:\Miniconda-x64\envs\python\Scripts;C:\Miniconda-x64\envs\python\Library\bin;C:\\Miniconda-x64\\Scripts;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer\;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files\Mercurial\;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\NUnit3\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\erl7.3\bin;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\120;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Amazon\AWSCLI\;C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\TShell\TShell\;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Apache\Maven\bin;C:\Program Files\LLVM\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\nodejs\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent\" was unexpected at this time.
Command exited with code 255
    ```

**Comment by jakirkham** [comment]
Looks like they switch to Boost 1.62.0. So should upgrade that [step]( https://github.com/ukoethe/vigra/blob/48c972b959cba8d29378042d6ae190d708492008/.travis.yml#L57 ) accordingly.

Though really it is probably worth giving some thought to switching to `conda` and getting these packages from conda-forge. We build `boost` to be compatible with `clang` on Mac and have C++11 support. Given we build `vigra` basically the same way it is being tested here, that should reduce the CI maintenance burden.

**Comment by stuarteberg** [comment]
Update (unrelated to CI discussion above):

I added another commit to this PR.  When using `relabelConsecutive()`, it is often useful to leave 0-valued pixels untouched, so I added an option for that and made it the default behavior.

**Comment by ukoethe** [comment]
We fixed the test server issues (thanks, @bluescarni!). Please merge with current master and rerun the checks.

**Comment by stuarteberg** [comment]
>Please merge with current master and rerun the checks.

Done.  One test failed.  It's the configuration of XCode w/ Python 3:

```
$ if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} -eq 3 ]]; then sudo ln -s /usr/local/bin/pip3 /usr/local/bin/pip ; fi

ln: /usr/local/bin/pip: File exists

The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} -eq 3 ]]; then sudo ln -s /usr/local/bin/pip3 /usr/local/bin/pip ; fi" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by ukoethe** [comment]
How is this possible? It worked for @bluescarni's PR today in the morning. Did they change the server configuration again in the meantime? I restarted the job to double-check...

**Comment by jakirkham** [comment]
Seems like you can just add a `-f` option to `ln`, no?

**Comment by jakirkham** [comment]
Also if you need that for that `ln` with `pip`, you will probably need it for `python` too.

**Comment by ukoethe** [comment]
@jakirkham: Since you contributed these lines (`git blame`: John Kirkham, 01/29/2016), you should know better than me. The corresponding link for python3 will be created in the next line. IMHO, when it worked in the morning and doesn't work now, this can only mean that the Travis maintainers added `/usr/local/bin/pip3` today. Stability doesn't seem to be their priority...

@stuarteberg: Can you try to comment the offending lines?

**Comment by jakirkham** [comment]
> Since you contributed these lines (git blame: John Kirkham, 01/29/2016), you should know better than me.

Yeah, that's why I'm suggesting to use force. 😄

It doesn't seem that they have added `/usr/local/bin/pip3`, but that someone (Travis or Homebrew) added`/usr/local/bin/pip`. So it seems like one solution is to overwrite it. Though it is a bit curious why this showed up as we have not installed `python`, but only installed `python3`. One possibility is `python` did get installed somehow. Another is Homebrew started doing the symlinking themselves.

In any event, I think it would be far less work for me and others if we just switch the CI to use `conda` on all fronts and use `conda-forge` to get everything that we need (including stuff `defaults` doesn't have). Going forward I'm finding it to be a bit too much work to dig into what Homebrew is doing and handle installation of things like Boost from third parties in this CI. It would be far less work for me to debug a `conda` install. If you would be ok with this switch, I could try possibly later this week or next.

**Comment by ukoethe** [comment]
> In any event, I think it would be far less work for me and others if we just switch the CI to use conda on all fronts and use conda-forge to get everything that we need (including stuff defaults doesn't have).

I certainly didn't suggest to use Homebrew. When we worked on the Travis script for Python3 testing on Mac, @jakirkham came up with a Homebrew-based solution because conda didn't work at the time. IIRC, some conda packages were missing or inconsistent. If conda is now suitable, I'll be more than happy to switch. Can you implement it?

**Comment by stuarteberg** [comment]
>Can you try to comment the offending lines?

I'm trying John's suggestion (`ln -s -f`).

In the meantime, I've added yet one more [little change](https://github.com/ukoethe/vigra/pull/391/commits/ae09f2862f4c6b3a4878d5b6c9baa19d36eff529) to this PR: I didn't like the vague error that `applyMapping()` throws if you provide an incomplete mapping to the function.  Now it raises a `KeyError`.  You may want to review the change, though.

**Comment by stuarteberg** [comment]
Phew, tests are finally passing.  I also fixed a bug I noticed today.  Ready for merge.

**Comment by jakirkham** [comment]
> IIRC, some conda packages were missing or inconsistent.

That's true. I thought there were other concerns too, but can't remember.

> If conda is now suitable, I'll be more than happy to switch. Can you implement it?

Absolutely! I think we will all be happier with this switch.

**Pull request merged**
