### PR TITLE
Modernize codebase for python 3+ (more)

### PR DESCRIPTION
**Pull request by a-detiste**
I'll check your issues. Per habit I allways start with a bit of cleansing with pyflakes & mypy.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
these look great thanks!

**Comment by hmaarrfk** [comment]
I merged without waiting for windows since the changes seemed sane. Its nice to have these cleanups in the master branch when starting with the more challenges fixes.

**Comment by a-detiste** [comment]
`vigranumpy/lib/__init__.py:443:13: undefined name 'vigra' `

**Comment by hmaarrfk** [comment]
is that a linter warning? how do yo uhit the code.... all the tests passed on linux....

**Comment by a-detiste** [comment]
numpy ended up loaded there anyway from one of the `*` import... but that's stretching luck

**Comment by hmaarrfk** [comment]
sorry i don't follow. if you make a PR i will review.

**Pull request merged**
