### PR TITLE
Add python 3.10 support

### PR DESCRIPTION
**Pull request by k-dominik**
Summary:

* dealt with deprecated `Iterable` import from `collections`

### CODE REVIEW

**Comment by hmeine** [comment]
The main change looks good to me.  I cannot check the CI setup changes, but to me they also look like updates & cleanups that should be merged.

What about the failed checks?  CMake failed with `vigranumpy dependencies NOT found while TEST_VIGRANUMPY=1` – can that be related to these changes?

**Comment by hmeine** [comment]
Do the CI pipeline changes supercede #490? Would you suggest merging that as well / before this one?

**Comment by k-dominik** [comment]
Hey @hmeine,

thanks a lot for looking into this!! I'll poke around CI some more (I have avoided azure pipelines so far, so I still have to catch up there a bit). My current issue would be activating the right toolset for python 3.10 (so finding the right `vcvarsall.bat` or using the right parameters to get 14.2, and I'm not sure where to find it :D).

I'll try to get this running and will ping you again once this is worth looking at (and I formed an opinion on #490).

Cheers and have a great weekend!

**Comment by hmaarrfk** [comment]
I merged in the fixes in the code from this branch  (trying to keep attribution).

I'm trying to fix the CIs in https://github.com/ukoethe/vigra/pull/514

**Comment by k-dominik** [comment]
thank you @hmaarrfk,

I'll close this PR then.

**Pull request closed without merging**
