### PR TITLE
Bump python minimum dependencies to 3.10 to follow nep29

### PR DESCRIPTION
**Pull request by hmaarrfk**
xref: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

### CODE REVIEW

**Comment by a-detiste** [comment]
So it's OK to remove old Python2 compat code ?

Stuff like this & more:

```
docsrc/makeFunctionIndex.py:from __future__ import division, print_function
config/vigra-config.in:from __future__ import division, print_function
vigranumpy/examples/blocking.py:from __future__ import print_function
vigranumpy/examples/grid_graph_shortestpath.py:from __future__ import print_function
vigranumpy/examples/merge_graph.py:from __future__ import print_function
vigranumpy/examples/non_local_mean_2d_color.py:from __future__ import print_function
vigranumpy/docsrc/conf.py.cmake2.in:from __future__ import division, print_function
vigranumpy/docsrc/conf.py.in:from __future__ import division, print_function
vigranumpy/lib/pyqt/viewer2svg.py:from __future__ import print_function
vigranumpy/lib/pyqt/imagewindow.py:from __future__ import print_function
vigranumpy/lib/__init__.py:from __future__ import division, print_function
vigranumpy/lib/arraytypes.py:from __future__ import print_function
vigranumpy/test/test_impex.py:from __future__ import division, print_function
vigranumpy/test/test4.py:from __future__ import division, print_function
vigranumpy/test/test_segmentation.py:﻿from __future__ import division, print_function
vigranumpy/test/test3.py:from __future__ import division, print_function
vigranumpy/test/test_rf.py:﻿from __future__ import division, print_function
vigranumpy/test/test1.py:from __future__ import division, print_function
vigranumpy/test/test_arraytypes.py:from __future__ import division, print_function
vigranumpy/test/test_color.py:from __future__ import division, print_function
vigranumpy/test/test_multidef.py:from __future__ import division, print_function
vigranumpy/test/test2.py:from __future__ import division, print_function
```

**Comment by hmaarrfk** [comment]
sure, lets get a few whitespace PRs in first...

**Comment by hmaarrfk** [comment]
it seems that there are other issues with `imp` if you want to take a stab at it feel free to do so.

I'm trying to get the whitespace cleanup working so that we can all use modern editors.....

If you can get it through, then go for it.

The CIs are slow, and I do want to wait for them to pass before merging things.

**Comment by hmaarrfk** [comment]
maybe those imp stuff came from nose.

**Comment by a-detiste** [comment]
Indeed. Nose stand right in the middle of a network of dead packages.

https://wiki.debian.org/Python/Dead%20Batteries#preview

image

**Comment by hmaarrfk** [comment]
@a-detiste do you care to comment on https://github.com/ukoethe/vigra/issues/569

**Pull request merged**
