### PR TITLE
Python3 port

### PR DESCRIPTION
**Pull request by ukoethe**
Still needs more testing and probably some minor fixes.

### CODE REVIEW

**Comment by jakirkham** [comment]
If you want, I can share a Travis CI matrix config for testing Python 3.

**Comment by ukoethe** [comment]
@jakirkham: Yes, please!

**Comment by ukoethe** [comment]
@jakirkham: Regarding Travis, I'd especially be interested in how to install and find `libpython*.so` and `libboost_python*.so` which **match** the Python version. I've tried Python 3.4 and 3.5, but cmake couldn't find `libpython*.so` and probably selected the wrong version of `libboost_python*.so`. However, the same cmake script worked on a local Ubuntu, and for Python 2.7 on Travis.

**Comment by jakirkham** [comment]
Sorry for the long delay. I think what you need here is quite simple. It seemed to work for me on Travis CI. Here is the PR ( https://github.com/ukoethe/vigra/pull/292 ).

**Comment by jakirkham** [comment]
Added another fix from my work with getting the Mac CI up. ( https://github.com/ukoethe/vigra/pull/297 )

**Comment by jakirkham** [comment]
Are there any outstanding items here before this can be merged into master?

**Comment by jakirkham** [comment]
Added a badge for AppVeyor against this PR. ( https://github.com/ukoethe/vigra/pull/313 )

**Comment by ukoethe** [comment]
A big thank-you all people who have contributed to this PR, especially @jakirkham and @FynnBe!

**Pull request merged**
